### PR TITLE
Document `sprite.h` w/ minor optimizations / fixes

### LINKED ISSUE #304: Document sprite.h with Doxygen

### PR DESCRIPTION
**Pull request by ricfehr3**
Document `sprite.h` and remove unused functions and variables.

Closes #304

### CODE REVIEW

**Comment by MeirGavish** [comment]
Cool, I will try to take a look tomorrow, I'm at my parents house and don't have a computer with me unfortunately.

File: include/sprite.h [hunk 1]
```diff
@@ -1,70 +1,318 @@
...
+ * @param a1 attribute 1 of OBJ_ATTR
+ * @param tid base tile index of sprite, part of attribute 2
+ * @param pb Palette-bank
+ * @param sprite_index index in memory
+ *
+ * @return Valid Sprite if allocations are successful.
+ *         Otherwise, return **NULL**.
+ */
 Sprite* sprite_new(u16 a0, u16 a1, u32 tid, u32 pb, int sprite_index);
-Sprite* affine_sprite_new(u16 a0, u16 a1, u32 tid, u32 pb);
```
Comment (MeirGavish) [inline include/sprite.h:41]: So this was just a function declaration with no implementation? Good call to remove

File: include/sprite.h [hunk 2]
```diff
@@ -1,70 +1,318 @@
...
 int sprite_get_layer(Sprite* sprite);
+
+/**
+ * @brief Get a Sprite's width and height
+ *
+ * @param sprite pointer to Sprite, cannot be **NULL**
+ * @param width pointer to variable to be set, cannot be **NULL**
+ * @param height pointer to variable to be set, cannot be **NULL**
+ *
+ * @return **true** is successful, **false** if otherwise. Upon success,
```
Comment (MeirGavish) [inline include/sprite.h]:
```suggestion
 * @return **true** if successful, **false** if otherwise. Upon success,
```
small typo

File: include/sprite.h [hunk 3]
```diff
@@ -1,70 +1,318 @@
...
+ *         `width` and `height` contain valid data, otherwise, the
+ *         variables are invalid.
```
Comment (MeirGavish) [inline include/sprite.h]: Invalid or unchanged?

File: include/sprite.h [hunk 4]
```diff
@@ -1,70 +1,318 @@
...
+ *
+ * @return Sprite pointer registered to `sprite_object` if successful,
+ *         otherwise return **NULL**. May be successful and **NULL** if there is no
+ *         Sprite registered to the SpriteObject.
+ */
 Sprite* sprite_object_get_sprite(SpriteObject* sprite_object);
+
+/**
+ * @brief Set the focus for SpriteObject (specifically for cards)
+ *        TODO: This should be moved to `card.h`
```
Comment (MeirGavish) [inline include/sprite.h]: I'm not sure this can or should be done, because jokers can also be focused. 
I think I did this for `selected` but `focused` is another matter.
The idea is that sprite objects can be focused so they can be bought in the shop for example but I see that cards use a focused array which should probably be switched to use this instead but it's a bigger refactor than I anticipated.

File: source/sprite.c [hunk 5]
```diff
@@ -328,8 +331,3 @@ bool sprite_object_get_dimensions(SpriteObject* sprite_object, int* width, int*
 
     return sprite_get_dimensions(sprite_object->sprite, width, height);
 }
-
-bool sprite_object_is_focused(SpriteObject* sprite_object)
-{
-    return sprite_object->focused;
-}
```
Comment (MeirGavish) [inline source/sprite.c:335]: It's unused but I don't know if it wouldn't be useful so I'd just leave it.

File: include/sprite.h (hunk 3 above)
Comment (ricfehr3) [reply include/sprite.h]: Unchanged is correct :+1:

File: include/sprite.h (hunk 4 above)
Comment (ricfehr3) [reply include/sprite.h]: That's fair. I'll remove the TODO.

File: include/sprite.h [hunk 6]
```diff
@@ -1,70 +1,326 @@
...
+ * @param sprite_object pointer to SpriteObject's registered Sprite. Cannot be **NULL**.
+ *
+ * @return Sprite pointer registered to `sprite_object` if successful,
+ *         otherwise return **NULL**. May be successful and **NULL** if there is no
+ *         Sprite registered to the SpriteObject.
+ */
 Sprite* sprite_object_get_sprite(SpriteObject* sprite_object);
+
+/**
+ * @brief Set the focus for SpriteObject (specifically for cards)
```
Comment (MeirGavish) [inline include/sprite.h:262]: Giving it some more thought I want to add something here, I approved and I'll merge and open another small PR for this.
